version: '3.9'

services:
  flask_ms:
    container_name: flask_ms
    build: .
    ports:
    - 5000:5000
    volumes:
    - ./:/app
    environment:
    - FLASK_ENV=development
    depends_on:
    - flask_db
    networks:
    - flaskNetwork

  flask_db:
    container_name: flask_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    volumes:
      - FlaskDbVolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flask
    networks:
    - flaskNetwork


volumes:
  FlaskDbVolume:
    driver: local


networks:
  flaskNetwork:
    driver: "bridge"
